name: Auto Build EXE

on: 
  push:
    tags:
    - 'v*'
  workflow_dispatch:
  #  branches: 
  #    - master

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
# This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      - name: Set up Python #安装python
        uses: actions/setup-python@v2.2.1
        with:
          python-version: 3.8
      - name: Install requirements #安装requests
        run: |
          pip install -r requirements.txt
          pip install pyinstaller
      - name: Build EXE
        run: |
          pyinstaller -F main.py
      - name: Upload EXE
        uses: actions/upload-artifact@v2.2.2
        with:
          name: ggn2pter
          path: dist/*.exe


